# SPDX-License-Identifier: Apache-2.0
"""M-2 plan ingestion — the M-1 plan-envelope contract, executable.

Parses/validates plan envelopes per ``docs/specs/plan-envelope-v1.md`` (v1 is
the authoring surface; ``plan-envelope-v0.md`` is the retired predecessor,
decodable only for frozen specimens — see S6) including the CD-1a governance
binding (§7) and admits them for execution. Format validation is not authority;
governance admission reads recorded status and witnesses — it never adjudicates.
"""

from maude.plan.envelope import (
    FROZEN_V0_PLAN_REFS,
    AdmissionRecord,
    CommandRequest,
    ExecutionRequestBlock,
    GovernanceBinding,
    PlanEnvelope,
    PlanRefusal,
    REFUSAL_GOVERNANCE_APPROVAL_UNVERIFIED,
    REFUSAL_GOVERNANCE_NOT_APPROVED,
    REFUSAL_GOVERNANCE_REF_MISMATCH,
    REFUSAL_INVALID_PLAN_ENVELOPE,
    REFUSAL_SUBMITTER_LIMITS_MISSING,
    admit_for_execution,
    parse_plan_envelope,
)
from maude.plan.document import (
    PLAN_DOCUMENT_SCHEMA,
    DeclaredWorldRequirementV1,
    DocumentConstraintsV1,
    PlanCommandV1,
    PlanDocumentError,
    PlanDocumentV1,
    PlanNodeV1,
    StructuredWorkV1,
    SubmitterV1,
    import_plan_envelope,
    new_node_id,
)
from maude.plan.operations import (
    PLAN_OPERATION_SCHEMA,
    AddNodeV1,
    PlanOperationError,
    PlanOperationV1,
    RemoveNodeV1,
    ReorderNodeV1,
    UpdateDocumentV1,
    UpdateNodeV1,
    apply_plan_operation,
)
from maude.plan.proposals import (
    PROPOSAL_REQUEST_SCHEMA,
    PROPOSAL_SCHEMA,
    PROVIDER_OUTPUT_SCHEMA,
    PlanEditProposalRequestV1,
    PlanEditProposalV1,
    ProposalError,
    ProposalScopeV1,
    ProviderDescriptorV1,
    preview_operation_sequence,
)

__all__ = [
    "FROZEN_V0_PLAN_REFS",
    "AdmissionRecord",
    "CommandRequest",
    "ExecutionRequestBlock",
    "GovernanceBinding",
    "PlanEnvelope",
    "PlanRefusal",
    "REFUSAL_GOVERNANCE_APPROVAL_UNVERIFIED",
    "REFUSAL_GOVERNANCE_NOT_APPROVED",
    "REFUSAL_GOVERNANCE_REF_MISMATCH",
    "REFUSAL_INVALID_PLAN_ENVELOPE",
    "REFUSAL_SUBMITTER_LIMITS_MISSING",
    "admit_for_execution",
    "parse_plan_envelope",
    "PLAN_DOCUMENT_SCHEMA",
    "DeclaredWorldRequirementV1",
    "DocumentConstraintsV1",
    "PlanCommandV1",
    "PlanDocumentError",
    "PlanDocumentV1",
    "PlanNodeV1",
    "StructuredWorkV1",
    "SubmitterV1",
    "import_plan_envelope",
    "new_node_id",
    "PLAN_OPERATION_SCHEMA",
    "AddNodeV1",
    "PlanOperationError",
    "PlanOperationV1",
    "RemoveNodeV1",
    "ReorderNodeV1",
    "UpdateDocumentV1",
    "UpdateNodeV1",
    "apply_plan_operation",
    "PROPOSAL_REQUEST_SCHEMA",
    "PROPOSAL_SCHEMA",
    "PROVIDER_OUTPUT_SCHEMA",
    "PlanEditProposalRequestV1",
    "PlanEditProposalV1",
    "ProposalError",
    "ProposalScopeV1",
    "ProviderDescriptorV1",
    "preview_operation_sequence",
]
